void pwd();
void echo(char *args[], int argc);
void cd(char *args[], int argc);
void discover(char *args[], int argc);
void ls(char *args[], int argc);
void pinfo(int pid);
char **getFileList(char *dir);
void jobs(char *args[], int argc);
void sendSignal(char *args[], int argc);
void resumeBG(char *args[], int argc);
void bringFG(char *args[], int argc);
